### ISSUE TITLE
vivado版本问题

### ISSUE THREAD

**Issue by CZZZHuan** [odin2985/AI-accerator-based-on-systolic#1]
你好，请问这个工程的vivado版本是多少？

**Comment by CZZZHuan** [comment]
我没有在我的vivado2018.3里找到xczu3eg-ubva530-2LV-e这一型号，我在想是不是vivado版本太低了

**Comment by odin2985** [comment]
vivado 2022.2


发件人： CZZZHuan
发送时间： 2024-07-19 21:52
收件人： odin2985/FPGA-CNN-accelerator-based-on-systolic-array
抄送： Subscribed
主题： [odin2985/FPGA-CNN-accelerator-based-on-systolic-array] vivado版本问题 (Issue #1)
你好，请问这个工程的vivado版本是多少？

**Comment by GuoningHuang** [comment]
vivado 2022.2

**Comment by GuoningHuang** [comment]
ip文件夹下面的ip核文件夹里面有怎么设置ip核的截图，可以根据那个设置ip核

**Comment by CZZZHuan** [comment]
好的谢谢！
